### ISSUE TITLE
Issues with $Variables not wrapped in braces { } 

### ISSUE THREAD

**Issue by kinglozzer** [kinglozzer/idea-silverstripe-plugin#11]
Likely a regression from https://github.com/kinglozzer/idea-silverstripe-plugin/commit/deee7f3622c6c9b5f4652fad090bfe8e0c3950f9

The following template parses `$Me` as a lookup, but the following `<` is parsed as `SS_TEXT` separately to the rest of the
 `% end_loop %>` statement

```
<% if $ElementControllers %>
    <% loop $ElementControllers %>
	   $Me
    <% end_loop %>
<% end_if %>
```

**Comment by kinglozzer** [comment]
Fixed in https://github.com/kinglozzer/idea-silverstripe-plugin/commit/0bf5dbae04ccb02af275236336e48fe2d30f8997

**Comment by beerbohmdo** [comment]
Seems to still not work:

![Auswahl_204](https://user-images.githubusercontent.com/905241/111750400-7a65e400-8893-11eb-8dea-723503e4dd82.png)

I first not spotted this, but it is exactly the same error:

![Auswahl_206](https://user-images.githubusercontent.com/905241/111750670-cadd4180-8893-11eb-8c87-06150231fb04.png)

Installed version is the 0.2.2

**Comment by kinglozzer** [comment]
Thanks @beerbohmdo, the original fix I did for this was the wrong approach. I’ve released 0.2.3 which should resolve this
